# Generated by Django 2.1.7 on 2019-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('mun_id', models.CharField(max_length=32, null=True)),
                ('t_max', models.IntegerField(null=True)),
                ('t_min', models.IntegerField(null=True)),
                ('prob_precipitacion', models.IntegerField(null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
