# Generated by Django 2.1.7 on 2019-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiempo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='t_max',
            new_name='maxima',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='t_min',
            new_name='minima',
        ),
        migrations.AddField(
            model_name='municipio',
            name='altitud',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='latitud',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='longitud',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='num_comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipio',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
