# Generated by Django 2.1.7 on 2019-05-06 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tiempo', '0002_auto_20190508_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(null=True)),
                ('color_letra', models.CharField(max_length=32, null=True)),
                ('tamaño_letra', models.CharField(max_length=32, null=True)),
                ('color_fondo', models.CharField(max_length=32, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
