# Generated by Django 2.1.7 on 2019-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiempo', '0005_municipio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='color_fondo',
            field=models.CharField(default='white', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='color_letra',
            field=models.CharField(default='black', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='tamaño_letra',
            field=models.CharField(default='normal', max_length=32, null=True),
        ),
    ]
