# Generated by Django 2.1.7 on 2019-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiempo', '0006_auto_20190512_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='dia',
            field=models.IntegerField(null=True),
        ),
    ]
