# Generated by Django 2.1.7 on 2019-05-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiempo', '0007_municipio_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navegador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(max_length=100, null=True)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
    ]
