# Generated by Django 2.1.7 on 2019-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiempo', '0008_navegador'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
